name: Daily build

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.1
        with:
          version: 2201.12.3

      - name: Cache Ballerina dependencies (Ubuntu)
        uses: actions/cache@v4
        id: cache-ballerina
        with:
          path: /home/runner/.ballerina/repositories/
          key: ${{ runner.os }}-ballerina-${{ github.base_ref || github.ref_name }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-ballerina-${{ github.base_ref || github.ref_name }}-

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

  windows-build:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Enable long paths for Git
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.1
        with:
          version: 2201.12.3

      - name: Cache Ballerina dependencies (Windows)
        uses: actions/cache@v4
        id: cache-ballerina
        with:
          path: C:\Users\runneradmin\.ballerina\repositories\
          key: ${{ runner.os }}-ballerina-${{ github.base_ref || github.ref_name }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-ballerina-${{ github.base_ref || github.ref_name }}-

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build
